apiVersion: apps/v1
kind: Deployment
metadata:
  name: reducepy
spec:
  selector:
    matchLabels:
      app: reducepy
  replicas: 3
  template:
    metadata:
      labels:
        app: reducepy
    spec:
      containers:
      - image: abdullahselek/reducepy:1.0
        name: reducepy
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
