apiVersion: v1
kind: Service
metadata:
  name: reducepy
spec:
  selector:
    app: reducepy
  type: NodePort
  ports:
  - nodePort: 31317
    port: 80
    protocol: TCP
    targetPort: 80
    targetPort: http
